FROM node:16-alpine

ARG MONGO_URL
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_CLOUDFRONT_URL
ARG AWS_BUCKET_NAME
ARG AWS_ACCESS_KEY_ID
ARG FIREBASE_PRIVATE_KEY
ARG FIREBASE_CLIENT_EMAIL
ARG FIREBASE_PROJECT_ID

WORKDIR /app

COPY ./package.json .
RUN npm install

COPY . .
RUN npm run build

CMD ["node", "dist/server.js"]